services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lakewatch:${LAKEWATCH_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      LAKEWATCH_HOST: 0.0.0.0
      LAKEWATCH_DB_FILE: /db_data/db.sqlite3
    volumes:
      - lakewatch-db-data:/db_data/



volumes:
  lakewatch-db-data:
    name: lakewatch-db-data
