services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lakewatch:${LAKEWATCH_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      LAKEWATCH_HOST: 0.0.0.0
      LAKEWATCH_DB_FILE: /db_data/db.sqlite3
      LAKEWATCH_RABBITMQ_HOST: rabbitmq
    volumes:
      - ./data:/db_data/
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  lakewatch-db-data:
    name: lakewatch-db-data
